### ISSUE TITLE
Sortering af spor-kategorier

### ISSUE THREAD

**Issue by BenByg** [filipbech/oaseprogram#1]
Kan sporene i rullegardinet sorteres efter:
1. Alders- og interessespor
2. Koncerter
3. Seminarer
4. Aktivitet

Samt alfabetisk under hver kategori?

**Comment by filipbech** [comment]
jeg viser dem i den rækkefølge jeg får dem fra jer :-D 
i forhold til fremtidige andre apps, med evt. andre kategorier, så tænker jeg det er smartest hvis i kan  sortere dem i jeres ende... gir det mening? og kan i det?

**Comment by BenByg** [comment]
Hmm... Ikke umiddelbart, da jeg kan se, at de nu er sorteret kategorier alfabetisk og spor under hver enkelt kategori efter oprettelsesdato.
Så skal det være noget med, at vi tilføjer et felt med et nummer, du kan sortere efter?

**Comment by filipbech** [comment]
Så er vi afhængige af Bo igen... Det synes jeg helt sikkert er den rigtige løsning fremad, men spørgsmålet er om vi kan gøre det nu eller vi skal hard-code en rækkefølge på dem nuher?

**Comment by BenByg** [comment]
Jeg tror, at vi skal fixe det på den hårde måde i denne omgang, så... Vi har spændt Bo hårdt for med noget tjek-ind app osv. for tiden. Så jeg vil ikke overbebyrde ham.
Hvis det er overkommeligt for dig at lave denne sortering, ville det være virkelig, virkelig lækkert - ellers må vi håbe at folk kan finde ud af det alligevel.

**Comment by filipbech** [comment]
så er det fixet: https://github.com/filipbech/oaseprogram/commit/0d5120e3a327bc6c1e38a5b82d293a8273114136 

På vej mod produktion

**Comment by BenByg** [comment]
Lækkert!!
