### ISSUE TITLE
Tilbage-knappen 'nulstiller'

### ISSUE THREAD

**Issue by BenByg** [filipbech/oaseprogram#3]
Jeg ved, at vi snakkede om det - og kan ikke helt huske, hvad vi nåede frem til eller hvad argumentet var...
Men flere nævner, at de synes det er træls at man fx kan lave en filtrering efter TeenTrack og hoppe frem til torsdag, vælge et event, måske finde ud af, at det ikke var det man ledte efter, for derefter at trykke på 'tilbage' - og så er det hele nulstillet, og man skal begynde sin søgning forfra.

**Comment by filipbech** [comment]
Lad os putte det på v2 listen - laver du den i øvrigt @BenByg ?

**Comment by filipbech** [comment]
Men umiddelbart er udfordringen/konsekvensen at alle filtreringer så kommer i "historien"... så hvis man skifter filtrering flere gange og så trykker tilbage, så kommer man tilbage til sidste filtrering (i stedet for at gå tilbage til den sidste side jeg var på). Det er heller ikke sikkert at det er hvad man vil...  hvad tænker du?

**Comment by BenByg** [comment]
Hmm, nej det lyder heller ikke helt optimalt... Jeg skriver det på listen til 2.0 👍
