### ISSUE TITLE
'Rodet' program-punkt-side

### ISSUE THREAD

**Issue by BenByg** [filipbech/oaseprogram#4]
Nogle har nævner at de enkelte programpunkters side er lidt rodede.

David W. og jeg har vendt om følgende kunne være en mulighed:

- Lade billederne (eventfoto, talerbillede eller sporlogo) fylde hele bredden, som de vidst også var til at begynde med.
- Have de praktiske informationer (spor, tidspunkt, taler, venue) over billedet og beskrivelsen under billedet, så der er en naturlig opdeling.
- Evt. bruge logo'er og fed skrifttype til at markere links (fx spor, taler og venue) frem for understregning. (Se evt. Davids oprindelige design-inspiration)

Vi tror at dette kunne gøre informationen på hver enkelt side dels lettere at overskue og dels lidt lækrere at se på.

![so2018_app_visning_dagsprogram_visning_af_event](https://user-images.githubusercontent.com/39982636/41456220-0af96e4e-7080-11e8-85f3-a79f5c57b18e.png)

**Comment by filipbech** [comment]
så er den også fixet - https://github.com/filipbech/oaseprogram/commit/de9618e2f91e9ff5b005eb4e1b65a7e3263efa88

Er på vej mod "live"

**Comment by BenByg** [comment]
Det er SÅ meget bedre!
