### ISSUE TITLE
"Hvad er?" --> "Info"

### ISSUE THREAD

**Issue by BenByg** [filipbech/oaseprogram#5]
Kan vi kalde menupunktet "Hvad er?" for "Info" i stedet? Det gør den lidt bredere, og giver os mulighed for fx at lave en ny kategori derinde med fx åbningstider for de forskellige butikker og madboder o.lign.

**Comment by filipbech** [comment]
done: https://github.com/filipbech/oaseprogram/commit/b6eb4b953da444768f47ac670942fc1a315008dd

er på vej ud nu!
